### ISSUE TITLE
Problem that all LEDs are glimpsing

### ISSUE THREAD

**Issue by hobbid** [ph1p/ikea-led-obegraensad#111]
Hi, 
i built your project and after some pitfalls i got it up and runing but i have an brightnes issue. it seems that all leds glimms and therefore there is no clear contrast an the quality of the clock or other screens are really bad. switching the brightness in the web frontend down not really help. 

To get it running i switched to pins as PIN 16 for the button was not available on my esp32 and with PIN 12  i had issues booting. After googlind i found out that for Pin12 it is stated: "boot fails if pulled high, strapping pin" so i switched to PIN 15.
so this is my pinout now.
`#ifdef ESP32
#define PIN_ENABLE 26
#define PIN_DATA 27
#define PIN_CLOCK 14
#define PIN_LATCH 25
#define PIN_BUTTON 5
#endif`

This is the board i used 
![IMG_1778](https://github.com/ph1p/ikea-led-obegraensad/assets/1017851/13c4db5c-1eac-46f2-9a8b-4af782d3f7ad)

And here is a image of the glimpsing leds:
![IMG_1780](https://github.com/ph1p/ikea-led-obegraensad/assets/1017851/db001d4b-9d5a-4134-8b37-f64956cc208c)

Any idea what is wrong why all leds are glimpsing ? 

Best regards

Dirk

**Comment by jaal2001** [comment]
Did you unsolder the chip on the display completely or just one pin? There have been cases, where the chip on the display needed to be removed completely.

**Comment by hobbid** [comment]
I desoldered the whole chip but unfortunately I ripped the first pad. Is that an issue ?

![IMG_1783](https://github.com/ph1p/ikea-led-obegraensad/assets/1017851/aa13bb65-fb40-4c95-a9e6-99f1dd72ad8a)

**Comment by jaal2001** [comment]
Probably not, but if you look right of your cable, it seems that there is a wire shortig multiple soldering pads. Maybe that is the issue.

**Comment by hobbid** [comment]
That did the trick ! With the pure eyes the wire was not really noticeable. Posting the photo and the comment from @jaal2001 did the trick! Thanks ! 🙏 
![IMG_1790](https://github.com/ph1p/ikea-led-obegraensad/assets/1017851/d9f4616f-e347-4e2e-ba51-9cd2c3d54c87)
