### ISSUE TITLE
Reconnect to WiFi in case of disconnection

### ISSUE THREAD

**Issue by craftbyte** [ph1p/ikea-led-obegraensad#14]
At the moment, if WiFi connection is lost, the ESP doesn't try to reconnect. This means the device has to be rebooted every time. Can something like the solutions at https://randomnerdtutorials.com/solved-reconnect-esp32-to-wifi/ be implemented?

**Comment by ph1p** [comment]
Sure, I'll take a look at it

**Comment by ph1p** [comment]
Closed, because of #41

**Comment by c64emulator** [comment]
Das Problem scheint nicht behoben:
Leider musste ich bei meinem neuen WLAN-Router einen Scheduler einrichten, der in jeder Nacht (nachdem die FRITZ!Box einen DSL-Reconnect durchgeführt hat) den Router neu bootet. Das war notwendig, weil das WLAN extrem unzuverlässig lief. 
Als Folge davon öffnet das LED-Panel nun seinen AP und wartet auf Eingaben.
