### ISSUE TITLE
Without dev board?

### ISSUE THREAD

**Issue by vidstige** [ph1p/ikea-led-obegraensad#24]
Is it possible to connect the Arduno directly without the dev board? I would like to keep my dev board on my desk

**Comment by ph1p** [comment]
What do you mean by dev board? You can easily wire up your arduino with the IKEA-PCB from your desk, you only have to use longer wires (:

**Comment by vidstige** [comment]
I mean without the the ESP32. Once I've it working, can I remove the ESP32 and connect the Arduino pins directly? Then I can close the back, etc.

**Comment by carlom74** [comment]
Can you/we make a pcb pluggable into the lamp connectors so we can simplify the hack and distribute it in a easier way? Ideally, the pluggable pcb should have a companion app, and be configurable (wifi) using Bluetooth... I'm a dreaming? :)

**Comment by BrookeDot** [comment]
It sounds like you're looking to replace the ESP32 with your own micocontroller. I'm working on a project (no where near done) which uses a custom PCB with the Particle Argon which uses this codebase as reference. I'll document the process more once complete. 

Beyond that, you'd likely have to make modifications to this code yourself or create your own PCB. Do you have an idea of what SOC you'd want to use if not the ESP? Any chip with SPI in theory _should_ work. 

As for an app, that's a whole other story. Maybe something like Adafruit.IO or platform.io could be used, but it would take development time. I don't want to speak for the project maintainers here, but it does feel out of scope. 

As we say at work "it's all just code" but depends on the amount of time and dedication to make things happen.

**Comment by ph1p** [comment]
I close the topic for now, if necessary it can be opened again.
