### ISSUE TITLE
Button does not loop properly with new update

### ISSUE THREAD

**Issue by YoshiFan501** [ph1p/ikea-led-obegraensad#31]
Pressing the button on the side shows the clock twice instead of the big clock as the second clock, and does not function on Weather

**Comment by ph1p** [comment]
Hi! Could you please try it again with the actual version?

**Comment by YoshiFan501** [comment]
Hello! I am curious what you mean with actual version. Is there a different official version besides cloning the repo and compiling?

**Comment by ph1p** [comment]
sorry for the misunderstanding, yes meant the main branch

**Comment by YoshiFan501** [comment]
That seemed to fix it!
