### ISSUE TITLE
add mDNS to server, to use http://ledscreen.local (ex.) URL

### ISSUE THREAD

**Issue by juliendorra** [ph1p/ikea-led-obegraensad#37]
mDNS (originally known as Bonjour) allows a server to announce its presence on a network by name. 

Practically, it means you can just type http://ledscreen.local (for example) in your browser and get to the screen without remembering the local ip. Useful for kids and friends.

It appears that the ESP32 Arduino library already offers mDNS: https://techtutorialsx.com/2020/04/18/esp32-advertise-service-with-mdns/

mDNS discovery of services works on Mac, iOS and Linux, but I'm not sure about Windows.

_(I'm posting a few issues as much for everyone here than for me, to keep a list of the enhancements I'd like to try and implement)_

**Comment by schw4rzlicht** [comment]
Please see #55 for my feature proposal.
