### ISSUE TITLE
What is the format of TZ_INFO?

### ISSUE THREAD

**Issue by Syco54645** [ph1p/ikea-led-obegraensad#42]
Reading the docs it is not clear what the value of TZ_INFO should be. Where can one find a list of TZ_INFO?

**Comment by luigipacheco** [comment]
Someone talks about it here:
https://www.esp32.com/viewtopic.php?t=5282

im still figuring out how to set it up for US

**Comment by luigipacheco** [comment]
this worked for me:
#define NTP_SERVER "pool.ntp.org"
#define TZ_INFO "UTC+4,M3.5.0/02:00:00,M10.5.0/03:00:00"


so if you change the first value before the coma to your UTC offset it should work

**Comment by ph1p** [comment]
Closed, because the new API lets you insert cities, long&lat etc.
