### ISSUE TITLE
Make a video of all Modes

### ISSUE THREAD

**Issue by DerPicknicker** [ph1p/ikea-led-obegraensad#5]
Hey, 

I am planning to buy that lamp only  to use it with your hack .. Could you provide a Video of all modes e.g Clock, Stars and all the other great modes.

Many thanks Cool work !!

**Comment by ph1p** [comment]
yesterday someone posted this on twitter, hope this helps you :) https://twitter.com/damjanmx/status/1605698205240291328

**Comment by DerPicknicker** [comment]
Cool! Do you have a picture of the clock mode ?

**Comment by ph1p** [comment]
![clock](https://user-images.githubusercontent.com/15351728/211204076-deee995e-c677-4571-bafe-a25017e21431.jpg)

Hope it answers your question and closes the issue (:
