### ISSUE TITLE
Flickering Panel with ESP32C3

### ISSUE THREAD

**Issue by hendrikreuhl** [ph1p/ikea-led-obegraensad#70]
Hey everyone,

first, thanks for the amazing development on this project.

I'm facing issues when using the Seeed-Xiao-ESP32C3

The pins i'm using:
```
PIN_ENABLE 3 // GPIO 3
PIN_DATA 20 // GPIO 20
PIN_CLOCK 7 // GPIO 7
PIN_LATCH 5 // GPIO 5
PIN_BUTTON 6 // GPIO 6
```

The software starts and the webinterface is also reachable.
When setting a mode (clock e.g.) some leds light up at the correct positions.
Some pixels are missing and do only light up if you dim the screen multiple times. Sometimes the leds also flicker.
Auto refreshing (on a new minute e.g.) does not work, random pixels light up sometimes.

When taking a look on the serial monitor, I get these error messages sometimes:

`[  2258][E][esp32-hal-gpio.c:102] __pinMode(): Invalid pin selected`
and
`[  2263][E][Preferences.cpp:503] getBytesLength(): nvs_get_blob len fail: data NOT_FOUND`

Does someone have any idea on how to fix this or might this be a board related issue?

Thanks

**Comment by wendehals** [comment]
Hello,

I had the same problem of flickering pixels. I solved the issue by completely removing the old controller chip. Beforehand I only desoldered the VCC pin of the old controller chip.

Greetings

**Comment by dsancheznet** [comment]
Hi guys,
I had the same problem and after almost driving me crazy I seitched the power source and now the problem is completely gone.
My guess is this appears with poor soldering contacts or a bad power brick.

Best regards
D.Sanchez

**Comment by gelse** [comment]
> My guess is this appears with poor soldering contacts or a bad power brick.

I had the same problem and solved it by re-soldering the contacts.
So - i would propose this issue to be closed, as it is NOT a software-bug.

**Comment by BrookeDot** [comment]
Perhaps the solution to mark this as "closed" is clarify in the readme file the suggested power supply and if flickering happens to check the contact? That seems like an easy win to help more people use this project and solve the problem themselves.

**Comment by ph1p** [comment]
Thanks for your suggestions. I added a "Trouble shooting" section to the readme file :)
