### ISSUE TITLE
Alternative button wiring

### ISSUE THREAD

**Issue by RBEGamer** [ph1p/ikea-led-obegraensad#79]
After unsoldering the old microcontroller from the PCB, it is possible to use the 7th pin for the button connection.
Using this the original wiring of the button can be the same. The other end of the button pin is already connected to ground on the PCB. Here the brown wire is connected to GPIO16 of the ESP32.

![IMG_7301](https://github.com/ph1p/ikea-led-obegraensad/assets/9280991/f7fec917-4d2e-491c-a430-502c7b140009)

**Comment by OldDroid** [comment]
Can confirm it works like a charm! Ty @RBEGamer

**Comment by Elump** [comment]
An alternative is to use the left pad (in printing direction the lower pad) of C6. Soldering is easier here compared to uC pin.

**Comment by RBEGamer** [comment]
![image](https://github.com/ph1p/ikea-led-obegraensad/assets/9280991/9bc9a219-8363-47bc-8ced-8df87aa565c0)

Works, you can see the traces between the two pads.
